###comments API
GET http://localhost:8080/api/notes/videoId/1
Accept: application/json

###tag API - get all tags
GET http://localhost:8080/api/tags
Accept: application/json

###tag API - get tag by id
GET http://localhost:8080/api/tags/tagId/952
Accept: application/json

###tag API - get tags on video by video id
GET http://localhost:8080/api/tags/videoId/1
Accept: application/json
