###video API - all
GET http://localhost:8080/api/video
Accept: application/json

###video API - name
GET http://localhost:8080/api/video/name/Zabotest.mp4
Accept: application/json

###frame API - id
GET http://localhost:8080/api/frame/id/10
Accept: application/json

###frame API - video
GET http://localhost:8080/api/frame/video/Zabotest.mp4
Accept: application/json

###frame API - video/frameNo
GET  http://localhost:8080/api/frame/video/Zabotest.mp4/frame/100
Accept: application/json

###tag API - all
GET http://localhost:8080/api/code
Accept: application/json

###tag API - id
GET http://localhost:8080/api/code/id/1752
Accept: application/json

###tag API - name
GET http://localhost:8080/api/code/name/name%20test
Accept: application/json

###tag API - video
GET http://localhost:8080/api/code/video/Zabotest.mp4
Accept: application/json