###video API - all with notes
GET http://localhost:8080/api/video?getNotes=true
Accept: application/json

###video API - all without notes
GET http://localhost:8080/api/video?getNotes=false
Accept: application/json

###video API - name with notes
GET http://localhost:8080/api/video/id/1?getNotes=true
Accept: application/json

###video API - name without notes
GET http://localhost:8080/api/video/id/1?getNotes=false
Accept: application/json

###frame API - id
GET http://localhost:8080/api/frame/id/5
Accept: application/json

###frame API - video
GET http://localhost:8080/api/frame/video/1
Accept: application/json

###frame API - video/frameNo
GET  http://localhost:8080/api/frame/video/1/frame/4
Accept: application/json

###tag API - all
GET http://localhost:8080/api/code
Accept: application/json

###tag API - id
GET http://localhost:8080/api/code/id/52
Accept: application/json

###tag API - name
GET http://localhost:8080/api/code/name/a%20b%20c
Accept: application/json

###tag API - video
GET http://localhost:8080/api/code/video/1
Accept: application/json

###overview API - all
GET localhost:8080/api/overview
Accept: application/json

###overview API - video
GET localhost:8080/api/overview/1
Accept: application/json